name: Build Linux

on:
  push:
    paths:
      - 'client/linux/**'
  workflow_dispatch:
  workflow_call:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libsdl2-dev

      - name: Build Terminal Client
        run: |
          cd client/linux/
          g++ -O3 -pthread ns-gamepad.cpp -o ns-gamepad -lSDL2

      - name: Build GUI Client
        run: |
          cd client/linux/
          g++ -std=c++17 -O2 -Wall ns-gui.cpp -o ns-gui $(pkg-config --cflags --libs gtk+-3.0) -lpthread -lSDL2

      - uses: actions/upload-artifact@v6
        with:
          name: linux-gamepad
          path: client/linux/ns-gamepad

      - uses: actions/upload-artifact@v6
        with:
          name: linux-gui
          path: client/linux/ns-gui
