name: Build macOS

on:
  push:
    paths:
      - 'client/mac/**'
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build Terminal Client
        run: |
          cd client/mac/
          clang++ -std=c++17 -ObjC++ \
            -framework GameController \
            -framework Foundation \
            -framework CoreGraphics \
            -framework CoreHaptics \
            ns-gamepad.mm -o ns-gamepad

      - name: Build GUI App Bundle
        run: |
          cd client/mac/
          bash build_gui.sh

      - uses: actions/upload-artifact@v6
        with:
          name: macos-gamepad
          path: client/mac/ns-gamepad

      - name: Package GUI App Bundle
        run: |
          cd client/mac/
          zip -r ns-pc-control-mac-gui.zip ns-gui.app

      - uses: actions/upload-artifact@v6
        with:
          name: macos-gui
          path: client/mac/ns-pc-control-mac-gui.zip