name: Build Windows

on:
  push:
    paths:
      - 'client/windows/**'
  workflow_dispatch:
  workflow_call:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Terminal Client (MinGW)
        shell: bash
        run: |
          cd client/windows/
          g++ -std=c++17 -O2 -Wall ns-gamepad.cpp -o ns-gamepad.exe -static -lws2_32 -lxinput

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build GUI Client (MSVC)
        shell: pwsh
        run: |
          cd client/windows
          rc /nologo ns-gui.rc
           cl /std:c++17 /O2 /EHsc /W3 ns-gui.cpp ns-gui.res /link ws2_32.lib xinput.lib setupapi.lib comctl32.lib user32.lib kernel32.lib gdi32.lib advapi32.lib /out:ns-gui.exe

      - name: Package
        shell: pwsh
        run: |
           Compress-Archive -Path client/windows/ns-gamepad.exe, client/windows/ns-gui.exe -DestinationPath client/windows/ns-pc-control-windows.zip -Force

      - uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: client/windows/ns-pc-control-windows.zip
