name: Build Pi Backend

on:
  push:
    paths:
      - 'backend/rpi/**'
  workflow_dispatch:
  workflow_call:

jobs:
  build-pi-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install ARM Cross-Compiler and zip
        run: sudo apt-get update && sudo apt-get install -y g++-aarch64-linux-gnu cmake zip
        
      - name: Build Pi Backend
        run: |
          cd backend/rpi
          mkdir build && cd build
          cmake .. -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++
          make
          cp ../setup_gadget.sh .
          zip ns-pc-control-raspberry-pi.zip ns-backend setup_gadget.sh
          
      - uses: actions/upload-artifact@v4
        with:
          name: rpi-artifact
          path: backend/rpi/build/ns-pc-control-raspberry-pi.zip